### PR TITLE
Fix in realtime-notifications blog post

### PR DESCRIPTION
**Pull request by pacorroX**
I tried to clone the project and saw with a support guy that this was not correct and not making that little change causes everything to not work.

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
Thank you @pacorroX for suggesting this change. It's a learning for me as well.

**Comment by rishi-raj-jain** [comment]
It did seem to work fine when I tried the whole set up with Vercel.

**Comment by pacorroX** [comment]
the demo link does not work right now

**Comment by rishi-raj-jain** [comment]
I had to take the deployment because someone abused the endpoint.

Screenshot 2024-02-24 at 5 27 04 PM

**Comment by rishi-raj-jain** [comment]
It'd be kind of you to update the PR with:

- Remove "Try the whole thing in action at https://upstash-nextjs-publish-messages-with-sse-example.vercel.app/" from the Demo section
- Remove the link from the table as rendered below:
Screenshot 2024-02-24 at 5 28 34 PM

**Review by enesakar — APPROVED** [review]

**Pull request merged**
