### PR TITLE
Updated icon.tsx for new Twitter icon "X"

### LINKED ISSUE #186: Need new SVG icon for "X" former "twitter"
for now we have the old "X" icon which is  "Twitter" icon. 

fix: change it to "X" icon by creating a SVG for "X" in Icon.tsx

### PR DESCRIPTION
**Pull request by karan-joshi-1**
added a new SVG icon for "X"

This PR will resolve #186   and will help resolve #86 for upstash-docs

### CODE REVIEW

**Comment by karan-joshi-1** [comment]
@enesakar @ademilter @sancar @mdogan can anyone look at this?

**Comment by enesakar** [comment]
hey @karan-joshi-1 our icon on upstash.com is already up to date. what does this PR do?

**Comment by rishi-raj-jain** [comment]
I think right now the bird is there for Twitter, while this PR intends to replace it with Twitter' new X icon.

Screenshot 2024-04-05 at 2 24 57 AM

**Comment by enesakar** [comment]
oh I see, thanks @karan-joshi-1

**Pull request merged**
