### PR TITLE
fix tables rendering using remark-gfm

### PR DESCRIPTION
**Pull request by rishi-raj-jain**

### CODE REVIEW

**Comment by ytkimirti** [comment]
Hey @rishi-raj-jain, can you explain the problem with current tables in the docs?

I just checked out [this table from docs](https://upstash.com/docs/redis/overall/rediscompatibility) and there doesn't seem to be any problem with it

**Review by ytkimirti — APPROVED** [review]

**Comment by ytkimirti** [comment]
A [page for reference](https://website-git-fork-rishi-raj-jain-fix-tables-upstash.vercel.app/blog/best-database-for-nextjs). LGTM

**Comment by rishi-raj-jain** [comment]
> A [page for reference](https://website-git-fork-rishi-raj-jain-fix-tables-upstash.vercel.app/blog/best-database-for-nextjs). LGTM

Yay!

**Comment by rishi-raj-jain** [comment]
> A [page for reference](https://website-git-fork-rishi-raj-jain-fix-tables-upstash.vercel.app/blog/best-database-for-nextjs). LGTM

Let's get this merged?

**Pull request merged**
